spin_manifest_version = 2

[application]
name = "place-timezone"
version = "0.0.1"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "place-timezone"

[component.place-timezone]
source = "target/wasm32-wasip1/release/place-timezone.wasm"
allowed_outbound_hosts = []

[component.place-timezone.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
